### ISSUE TITLE
fix(form): if complex, non-optional attribute has default value, use that instead of instantiateEntity

### ISSUE THREAD

**Issue by ingeridhellen** [equinor/dm-core-packages#470]
Also, for primitive, optional values the default value should in some way be reflected in the form (parent default supersedes the child default)

**Comment by collinlokken** [comment]
If I understand correctly, there is a scenario where a required attribute should be added and the default value should be used for this. But shouldn't it be impossible to have an entity without a required attribute in the first place? Thus [Open] button should be the only operation that makes sense, in my mind, because it already exist.

To me this only makes sense for _optional_ attributes, as you want to use the [Add and Save] button.

**Comment by eoaksnes** [comment]
Add validation before adding the default value.
